import { SUPPORT_TOPICS } from './supportTickets'

export const SAMPLE_TICKETS = [
  {
    id: 'ticket-001',
    ticketNumber: 'TKT-20481',
    customerName: 'Ama Serwaa',
    customerEmail: 'ama.serwaa@gmail.com',
    topic: SUPPORT_TOPICS.orders,
    subject: SUPPORT_TOPICS.orders,
    preview: 'I placed order ORD-10482 three days ago and have not received a delivery update.',
    status: 'pending',
    unreadCount: 1,
    orderId: 'ord-10482',
    orderNumber: 'ORD-10482',
    updatedAt: '2026-09-21T09:15:00Z',
    createdAt: '2026-09-19T14:30:00Z',
    messages: [
      {
        id: 'msg-001',
        sender: 'customer',
        text: 'I placed order ORD-10482 three days ago and have not received a delivery update. Can you tell me where it is?',
        sentAt: '2026-09-19T14:30:00Z',
      },
      {
        id: 'msg-002',
        sender: 'support',
        text: 'Hello Ama, I checked ORD-10482. It left the seller yesterday and is with the courier.',
        sentAt: '2026-09-19T16:02:00Z',
      },
      {
        id: 'msg-003',
        sender: 'customer',
        text: 'It still shows as processing in my account. Can you confirm the tracking update?',
        sentAt: '2026-09-21T09:15:00Z',
      },
    ],
  },
  {
    id: 'ticket-002',
    ticketNumber: 'TKT-20490',
    customerName: 'Kwame Mensah',
    customerEmail: 'kwame.m@outlook.com',
    topic: SUPPORT_TOPICS.returns,
    subject: SUPPORT_TOPICS.returns,
    preview: 'I ordered the midnight black variant but received navy blue and would like a refund.',
    status: 'open',
    unreadCount: 1,
    orderId: 'ord-10391',
    orderNumber: 'ORD-10391',
    updatedAt: '2026-09-20T16:45:00Z',
    createdAt: '2026-09-20T16:45:00Z',
    messages: [
      {
        id: 'msg-004',
        sender: 'customer',
        text: 'I ordered the midnight black variant on ORD-10391 but received navy blue. I would like to return it for a refund.',
        sentAt: '2026-09-20T16:45:00Z',
      },
    ],
  },
  {
    id: 'ticket-003',
    ticketNumber: 'TKT-20472',
    customerName: 'Efua Boateng',
    customerEmail: 'efua.b@yahoo.com',
    topic: SUPPORT_TOPICS.products,
    subject: SUPPORT_TOPICS.products,
    preview: 'Does the standing desk fit in a room with a 2.4m ceiling?',
    status: 'closed',
    unreadCount: 0,
    orderId: null,
    orderNumber: null,
    updatedAt: '2026-09-18T11:20:00Z',
    createdAt: '2026-09-17T09:00:00Z',
    messages: [
      {
        id: 'msg-005',
        sender: 'customer',
        text: 'Does the standing desk fit in a room with a 2.4m ceiling? What is the maximum height when it is fully extended?',
        sentAt: '2026-09-17T09:00:00Z',
      },
      {
        id: 'msg-006',
        sender: 'support',
        text: 'The desk extends to 125cm, so it fits comfortably under a 2.4m ceiling. I am closing this request now that the measurement is confirmed.',
        sentAt: '2026-09-18T11:20:00Z',
      },
    ],
  },
  {
    id: 'ticket-004',
    ticketNumber: 'TKT-20495',
    customerName: 'Kofi Asante',
    customerEmail: 'kofi.a@gmail.com',
    topic: SUPPORT_TOPICS.payments,
    subject: SUPPORT_TOPICS.payments,
    preview: 'My card was charged for ORD-10502 but the order still says payment failed.',
    status: 'open',
    unreadCount: 1,
    orderId: 'ord-10502',
    orderNumber: 'ORD-10502',
    updatedAt: '2026-09-21T13:10:00Z',
    createdAt: '2026-09-21T13:10:00Z',
    messages: [
      {
        id: 'msg-007',
        sender: 'customer',
        text: 'My card was charged for ORD-10502 but the order still says payment failed. Please confirm whether the payment went through.',
        sentAt: '2026-09-21T13:10:00Z',
      },
    ],
  },
  {
    id: 'ticket-005',
    ticketNumber: 'TKT-20460',
    customerName: 'Abena Osei',
    customerEmail: 'abena.o@gmail.com',
    topic: SUPPORT_TOPICS.orders,
    subject: SUPPORT_TOPICS.orders,
    preview: 'Can I change the delivery address for order ORD-10455?',
    status: 'closed',
    unreadCount: 0,
    orderId: 'ord-10455',
    orderNumber: 'ORD-10455',
    updatedAt: '2026-09-16T10:00:00Z',
    createdAt: '2026-09-15T18:00:00Z',
    messages: [
      {
        id: 'msg-008',
        sender: 'customer',
        text: 'Can I change the delivery address for order ORD-10455? I moved to 14 Ring Road East, Accra.',
        sentAt: '2026-09-15T18:00:00Z',
      },
      {
        id: 'msg-009',
        sender: 'support',
        text: 'The address on ORD-10455 is updated. The courier will deliver to 14 Ring Road East, Accra.',
        sentAt: '2026-09-16T10:00:00Z',
      },
    ],
  },
]
