export const EMPTY_ANALYTICS_SUMMARY = {
  revenue: 0,
  orders: 0,
  customers: 0,
  conversionRate: 0,
  avgOrderValue: 0,
  returnRate: 0,
}

export const EMPTY_ANALYTICS = {
  summary: { ...EMPTY_ANALYTICS_SUMMARY },
  previousSummary: { ...EMPTY_ANALYTICS_SUMMARY },
  revenueTimeline: [],
  categoryBreakdown: [],
  topProducts: [],
  salesByRegion: [],
  customerGrowth: [],
  fulfillmentStats: { fulfilled: 0, pending: 0, cancelled: 0, returned: 0 },
}

export const DEV_ANALYTICS = {
  summary: {
    revenue: 128450,
    orders: 342,
    customers: 186,
    conversionRate: 3.8,
    avgOrderValue: 375.58,
    returnRate: 2.4,
  },
  previousSummary: {
    revenue: 98200,
    orders: 278,
    customers: 154,
    conversionRate: 3.2,
    avgOrderValue: 353.24,
    returnRate: 2.9,
  },
  revenueTimeline: [
    { label: 'Jan', revenue: 8400, orders: 28 },
    { label: 'Feb', revenue: 9200, orders: 31 },
    { label: 'Mar', revenue: 11200, orders: 38 },
    { label: 'Apr', revenue: 9800, orders: 32 },
    { label: 'May', revenue: 12400, orders: 41 },
    { label: 'Jun', revenue: 11800, orders: 39 },
    { label: 'Jul', revenue: 14200, orders: 47 },
    { label: 'Aug', revenue: 13600, orders: 44 },
    { label: 'Sep', revenue: 15100, orders: 49 },
    { label: 'Oct', revenue: 16800, orders: 54 },
    { label: 'Nov', revenue: 18200, orders: 58 },
    { label: 'Dec', revenue: 19550, orders: 61 },
  ],
  categoryBreakdown: [
    { name: 'Furniture', value: 48200, color: '#c73b2d' },
    { name: 'Electronics', value: 31800, color: '#0f8f9c' },
    { name: 'Home & Living', value: 24600, color: '#f97316' },
    { name: 'Office Supplies', value: 15400, color: '#8b5cf6' },
    { name: 'Other', value: 8450, color: '#64748b' },
  ],
  topProducts: [
    { id: 'p1', name: 'Ergonomic Office Chair', category: 'Furniture', units: 48, revenue: 28800, trend: 12 },
    { id: 'p2', name: 'Adjustable Standing Desk', category: 'Furniture', units: 32, revenue: 22400, trend: 8 },
    { id: 'p3', name: 'Wireless Bluetooth Headphones', category: 'Electronics', units: 67, revenue: 16750, trend: -3 },
    { id: 'p4', name: 'Memory Foam Pillow', category: 'Home & Living', units: 89, revenue: 8900, trend: 15 },
    { id: 'p5', name: 'Ceramic Planter Set', category: 'Home & Living', units: 54, revenue: 6480, trend: 5 },
    { id: 'p6', name: 'USB-C Hub 7-in-1', category: 'Electronics', units: 41, revenue: 6150, trend: -1 },
  ],
  salesByRegion: [
    { id: 'greater-accra', name: 'Greater Accra', revenue: 56200, orders: 148 },
    { id: 'ashanti', name: 'Ashanti', revenue: 31800, orders: 86 },
    { id: 'western', name: 'Western', revenue: 15400, orders: 41 },
    { id: 'eastern', name: 'Eastern', revenue: 12800, orders: 34 },
    { id: 'central', name: 'Central', revenue: 8450, orders: 22 },
    { id: null, name: 'Other', revenue: 3800, orders: 11 },
  ],
  customerGrowth: [
    { label: 'Jan', newCustomers: 12, returning: 8 },
    { label: 'Feb', newCustomers: 14, returning: 10 },
    { label: 'Mar', newCustomers: 18, returning: 12 },
    { label: 'Apr', newCustomers: 15, returning: 14 },
    { label: 'May', newCustomers: 22, returning: 16 },
    { label: 'Jun', newCustomers: 19, returning: 18 },
    { label: 'Jul', newCustomers: 24, returning: 20 },
    { label: 'Aug', newCustomers: 21, returning: 22 },
    { label: 'Sep', newCustomers: 26, returning: 24 },
    { label: 'Oct', newCustomers: 28, returning: 26 },
    { label: 'Nov', newCustomers: 31, returning: 28 },
    { label: 'Dec', newCustomers: 34, returning: 30 },
  ],
  fulfillmentStats: { fulfilled: 298, pending: 24, cancelled: 12, returned: 8 },
}
