export const GHANA_DISTRICTS = {
  'greater accra': [
    'Accra Metropolitan',
    'Tema Metropolitan',
    'Ga East',
    'Ga West',
    'Ga Central',
    'Ga South',
    'Ledzokuku',
    'Krowor',
    'La Dade-Kotopon',
    'La Nkwantanang Madina',
    'Adentan',
    'Ashaiman',
    'Shai-Osudoku',
    'Ningo-Prampram',
  ],
  ashanti: [
    'Kumasi Metropolitan',
    'Asokwa Municipal',
    'Oforikrom Municipal',
    'Kwadaso Municipal',
    'Suame Municipal',
    'Old Tafo Municipal',
    'Asokore Mampong Municipal',
    'Ejisu Municipal',
    'Obuasi Municipal',
    'Mampong Municipal',
    'Bekwai Municipal',
  ],
  western: [
    'Sekondi-Takoradi Metropolitan',
    'Ahanta West',
    'Nzema East',
    'Ellembelle',
    'Tarkwa-Nsuaem',
    'Prestea Huni Valley',
    'Wassa Amenfi East',
    'Wassa Amenfi West',
  ],
  central: [
    'Cape Coast Metropolitan',
    'Komenda-Edina-Eguafo-Abirem',
    'Abura-Asebu-Kwamankese',
    'Mfantsiman',
    'Agona East',
    'Agona West',
    'Gomoa East',
    'Gomoa West',
    'Effutu',
    'Awutu Senya East',
    'Awutu Senya West',
  ],
  eastern: [
    'New Juaben South Municipal',
    'New Juaben North Municipal',
    'Akuapem North',
    'Akuapem South',
    'Yilo Krobo',
    'Lower Manya Krobo',
    'Upper Manya Krobo',
    'Fanteakwa North',
    'Kwahu South',
    'Kwahu East',
    'Nsawam Adoagyiri Municipal',
  ],
  northern: [
    'Tamale Metropolitan',
    'Sagnarigu Municipal',
    'Yendi Municipal',
    'Gushegu',
    'Karaga',
    'Mion',
    'Nanumba North',
    'Nanumba South',
    'Savelugu',
    'Nanton',
  ],
  volta: [
    'Ho Municipal',
    'Hohoe Municipal',
    'Keta Municipal',
    'Ketu South',
    'Ketu North',
    'Anloga',
    'Akatsi North',
    'Akatsi South',
    'South Tongu',
    'Central Tongu',
    'North Tongu',
  ],
  'upper east': ['Bolgatanga Municipal', 'Bongo', 'Bawku Municipal', 'Bawku West', 'Binduri', 'Garu', 'Tempane', 'Pusiga', 'Kassena Nankana Municipal'],
  'upper west': ['Wa Municipal', 'Wa East', 'Wa West', 'Nadowli-Kaleo', 'Lawra', 'Jirapa', 'Lambussie Karni', 'Sissala East', 'Sissala West'],
  bono: ['Sunyani Municipal', 'Sunyani West', 'Berekum Municipal', 'Berekum East', 'Dormaa Central Municipal', 'Dormaa East', 'Dormaa West', 'Jaman North', 'Jaman South'],
  'bono east': ['Techiman Municipal', 'Techiman North', 'Kintampo North', 'Kintampo South', 'Nkoranza North', 'Nkoranza South', 'Atebubu-Amantin', 'Sene East', 'Sene West'],
  ahafo: ['Asunafo North Municipal', 'Asunafo South', 'Asutifi North', 'Asutifi South', 'Tano North', 'Tano South'],
  'western north': ['Sefwi Wiawso Municipal', 'Bibiani-Anhwiaso-Bekwai Municipal', 'Juaboso', 'Bia East', 'Bia West', 'Aowin Municipal', 'Suaman'],
  oti: ['Krachi East Municipal', 'Krachi West', 'Krachi Nchumuru', 'Nkwanta North', 'Nkwanta South Municipal', 'Biakoye', 'Jasikan', 'Kadjebi', 'Guan'],
  'north east': ['Nalerigu-Gambaga Municipal', 'Mamprugu Moagduri', 'Yunyoo-Nasuan', 'Bunkpurugu-Nakpanduri', 'Chereponi', 'West Mamprusi Municipal', 'East Mamprusi Municipal'],
  savannah: ['Damongo Municipal', 'West Gonja Municipal', 'Central Gonja', 'East Gonja Municipal', 'North Gonja', 'North East Gonja', 'Sawla-Tuna-Kalba'],
}

export function getDistrictsByRegion(region) {
  if (!region) return []
  return GHANA_DISTRICTS[region.toLowerCase()] ?? []
}
