import {
  BarChart3,
  Bell,
  CircleDollarSign,
  MessageSquare,
  Package,
  ShoppingBag,
  Star,
  Tag,
  Truck,
} from 'lucide-react'

export const NOTIFICATION_TYPES = {
  new_order: {
    label: 'New order',
    category: 'orders',
    ctaLabel: 'View Order',
    defaultTo: '/orders',
    icon: ShoppingBag,
    iconWrap: 'bg-sky-50 text-sky-700 ring-sky-100',
  },
  order_status: {
    label: 'Order update',
    category: 'orders',
    ctaLabel: 'View Order',
    defaultTo: '/orders',
    icon: Truck,
    iconWrap: 'bg-sky-50 text-sky-700 ring-sky-100',
  },
  customer_message: {
    label: 'Customer message',
    category: 'customers',
    ctaLabel: 'View Message',
    defaultTo: '/messages',
    icon: MessageSquare,
    iconWrap: 'bg-violet-50 text-violet-700 ring-violet-100',
  },
  product_review: {
    label: 'Product review',
    category: 'products',
    ctaLabel: 'View Review',
    defaultTo: '/reviews',
    icon: Star,
    iconWrap: 'bg-amber-50 text-amber-700 ring-amber-100',
  },
  customer_review: {
    label: 'Product review',
    category: 'products',
    ctaLabel: 'View Review',
    defaultTo: '/reviews',
    icon: Star,
    iconWrap: 'bg-amber-50 text-amber-700 ring-amber-100',
  },
  product_update: {
    label: 'Product update',
    category: 'products',
    ctaLabel: 'View Product',
    defaultTo: '/products',
    icon: Package,
    iconWrap: 'bg-amber-50 text-amber-800 ring-amber-100',
  },
  low_stock: {
    label: 'Low stock',
    category: 'products',
    ctaLabel: 'View Product',
    defaultTo: '/products',
    icon: Package,
    iconWrap: 'bg-amber-50 text-amber-800 ring-amber-100',
  },
  sales_analytics: {
    label: 'Sales insight',
    category: 'platform',
    ctaLabel: 'View Analytics',
    defaultTo: '/analytics',
    icon: BarChart3,
    iconWrap: 'bg-slate-100 text-slate-700 ring-slate-200',
  },
  promotion_status: {
    label: 'Promotion',
    category: 'promotions',
    ctaLabel: 'View Promotion',
    defaultTo: '/promotions',
    icon: Tag,
    iconWrap: 'bg-orange-50 text-orange-700 ring-orange-100',
  },
  payout_processed: {
    label: 'Payout',
    category: 'payouts',
    ctaLabel: 'View Payout',
    defaultTo: '/finance',
    icon: CircleDollarSign,
    iconWrap: 'bg-emerald-50 text-emerald-700 ring-emerald-100',
  },
  platform_update: {
    label: 'Platform',
    category: 'platform',
    ctaLabel: 'Learn More',
    defaultTo: '/help',
    icon: Bell,
    iconWrap: 'bg-slate-100 text-slate-700 ring-slate-200',
  },
}

export const MOCK_VENDOR_NOTIFICATIONS = []

export const DEV_VENDOR_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'new_order',
    title: 'New order received',
    message: 'ORD-20491 — Wireless Earbuds Pro. GH₵ 490.00 from Ama Serwaa.',
    dateTime: '2026-09-07T13:42:00',
    read: false,
    link: '/orders',
  },
  {
    id: 'notif-002',
    type: 'customer_message',
    title: 'New customer message',
    message: 'Kwame Mensah asked about a colour mismatch on order ORD-10391.',
    dateTime: '2026-09-07T12:18:00',
    read: false,
    link: '/messages',
  },
  {
    id: 'notif-003',
    type: 'order_status',
    title: 'Order marked as shipped',
    message: 'ORD-20478 is out for delivery. The customer will receive tracking shortly.',
    dateTime: '2026-09-07T10:05:00',
    read: false,
    link: '/orders',
  },
  {
    id: 'notif-004',
    type: 'product_review',
    title: 'Product review received',
    message: 'Efua Boateng rated Ergonomic Office Chair — 5 stars.',
    dateTime: '2026-09-07T08:51:00',
    read: false,
    link: '/reviews',
  },
  {
    id: 'notif-005',
    type: 'payout_processed',
    title: 'Payout processed',
    message: 'GH₵ 3,240.50 was sent to your GTBank account ending 4821.',
    dateTime: '2026-09-07T07:30:00',
    read: false,
    link: '/finance',
  },
  {
    id: 'notif-006',
    type: 'new_order',
    title: 'New order received',
    message: 'ORD-20488 — Standing Desk Frame. GH₵ 1,250.00 from Yaw Owusu.',
    dateTime: '2026-09-06T19:14:00',
    read: false,
    link: '/orders',
  },
  {
    id: 'notif-007',
    type: 'product_update',
    title: 'Product low in stock',
    message: 'Bluetooth Speaker Mini has only 2 units left. Restock to avoid lost sales.',
    dateTime: '2026-09-06T16:40:00',
    read: false,
    link: '/products',
  },
  {
    id: 'notif-008',
    type: 'promotion_status',
    title: 'Flash sale approved',
    message: 'Your Weekend Audio Sale is approved and scheduled to go live Friday 6:00 AM.',
    dateTime: '2026-09-06T11:22:00',
    read: false,
    link: '/promotions',
  },
  {
    id: 'notif-009',
    type: 'sales_analytics',
    title: 'Weekend sales were up 18%',
    message: 'Orders rose versus last weekend. Office furniture led conversion.',
    dateTime: '2026-09-06T09:00:00',
    read: true,
    link: '/analytics',
  },
  {
    id: 'notif-010',
    type: 'platform_update',
    title: 'Settlement calendar update',
    message: 'Payouts now process every Tuesday and Friday. Learn how this affects your schedule.',
    dateTime: '2026-09-05T15:10:00',
    read: true,
    link: '/help',
  },
  {
    id: 'notif-011',
    type: 'customer_message',
    title: 'New customer message',
    message: 'Ama Serwaa is asking for a delivery update on ORD-10482.',
    dateTime: '2026-09-05T12:44:00',
    read: false,
    link: '/messages',
  },
  {
    id: 'notif-012',
    type: 'order_status',
    title: 'Order delivered',
    message: 'ORD-20461 was marked delivered. Ask the customer for a review while it is fresh.',
    dateTime: '2026-09-05T09:18:00',
    read: true,
    link: '/orders',
  },
  {
    id: 'notif-013',
    type: 'product_review',
    title: 'Product review received',
    message: 'Kojo Addo rated USB-C Hub 7-in-1 — 3 stars, mentioning missing adapters.',
    dateTime: '2026-09-04T17:36:00',
    read: true,
    link: '/reviews',
  },
  {
    id: 'notif-014',
    type: 'promotion_status',
    title: 'Promotion needs changes',
    message: 'Clearance on Running Sneakers was returned. Discount exceeds the allowed range.',
    dateTime: '2026-09-04T13:05:00',
    read: false,
    link: '/promotions',
  },
  {
    id: 'notif-015',
    type: 'product_update',
    title: 'Listing approved',
    message: 'Smart Watch Series 4 is now live on EZ-Mall after catalogue review.',
    dateTime: '2026-09-03T11:50:00',
    read: true,
    link: '/products',
  },
  {
    id: 'notif-016',
    type: 'payout_processed',
    title: 'Payout settled',
    message: 'Your 28 Aug payout of GH₵ 1,875.00 is complete. View the remittance on Finance.',
    dateTime: '2026-09-02T08:20:00',
    read: true,
    link: '/finance',
  },
  {
    id: 'notif-017',
    type: 'new_order',
    title: 'New order received',
    message: 'ORD-20440 — Running Sneakers. GH₵ 340.00 from Akosua Frimpong.',
    dateTime: '2026-09-01T18:02:00',
    read: true,
    link: '/orders',
  },
  {
    id: 'notif-018',
    type: 'platform_update',
    title: 'Seller policy reminder',
    message: 'Response-time targets for customer messages are now 24 hours on business days.',
    dateTime: '2026-08-30T10:00:00',
    read: true,
    link: '/help',
  },
  {
    id: 'notif-019',
    type: 'sales_analytics',
    title: 'August performance snapshot',
    message: 'You closed August with 146 orders and a 4.6 store rating. See the full report.',
    dateTime: '2026-08-29T09:15:00',
    read: true,
    link: '/analytics',
  },
  {
    id: 'notif-020',
    type: 'customer_message',
    title: 'New customer message',
    message: 'Nana Adwoa asked whether the standing desk fits a 2.4m ceiling.',
    dateTime: '2026-08-28T16:27:00',
    read: true,
    link: '/messages',
  },
  {
    id: 'notif-021',
    type: 'product_update',
    title: 'Image quality flagged',
    message: 'Replace the first image on Leather Desk Mat. Listings with lifestyle shots convert better.',
    dateTime: '2026-08-27T14:12:00',
    read: true,
    link: '/products',
  },
  {
    id: 'notif-022',
    type: 'promotion_status',
    title: 'Today’s Deal ended',
    message: 'Office Essentials Deal ended after 38 units sold. Duplicate it for next week.',
    dateTime: '2026-08-26T21:00:00',
    read: true,
    link: '/promotions',
  },
]

export const VENDOR_NOTIFICATIONS = MOCK_VENDOR_NOTIFICATIONS
