function toRecentOrderPreview(order) {
  const firstItem = order.items[0]

  return {
    id: order.id,
    productName: firstItem?.productName ?? 'Multiple items',
    thumbnail: firstItem?.image ?? null,
    dateTime: order.orderDate,
    status: order.orderStatus,
    amount: order.totalAmount,
  }
}

export const MOCK_VENDOR_ORDERS = [
  {
    id: 'ORD-1048',
    orderNumber: 'ORD-1048',
    orderDate: '2026-06-16T14:22:00',
    customer: {
      name: 'Ama Mensah',
      email: 'ama.mensah@example.com',
      phone: '+233 24 123 4567',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-web-earbuds',
        productName: 'Wireless Earbuds Pro',
        sku: 'WEB-PRO-001',
        image: 'https://images.unsplash.com/photo-1590658268037-6bf3f7f2b8fd?w=120&h=120&fit=crop',
        quantity: 2,
        unitPrice: 245,
        totalPrice: 490,
      },
    ],
    productsCount: 2,
    subtotal: 490,
    deliveryFee: 25,
    discount: 0,
    totalAmount: 515,
    paymentStatus: 'paid',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-882341',
    orderStatus: 'pending',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '14 Ring Road East, Osu',
      region: 'Greater Accra',
      city: 'Accra',
      notes: 'Call before delivery.',
    },
  },
  {
    id: 'ORD-1047',
    orderNumber: 'ORD-1047',
    orderDate: '2026-06-16T11:05:00',
    customer: {
      name: 'Kwame Boateng',
      email: 'kwame.b@example.com',
      phone: '+233 55 987 6543',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-smart-watch',
        productName: 'Smart Watch Series 4',
        sku: 'SW-S4-BLK',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 890,
        totalPrice: 890,
      },
    ],
    productsCount: 1,
    subtotal: 890,
    deliveryFee: 30,
    discount: 30,
    totalAmount: 890,
    paymentStatus: 'paid',
    paymentMethod: 'Card',
    transactionReference: 'TXN-CARD-441902',
    orderStatus: 'processing',
    deliveryMethod: 'Express Delivery',
    delivery: {
      address: '22 Independence Avenue',
      region: 'Ashanti',
      city: 'Kumasi',
      notes: '',
    },
  },
  {
    id: 'ORD-1046',
    orderNumber: 'ORD-1046',
    orderDate: '2026-06-15T18:40:00',
    customer: {
      name: 'Efua Adjei',
      email: 'efua.adjei@example.com',
      phone: '+233 20 456 7890',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-running-sneakers',
        productName: 'Running Sneakers',
        sku: 'RUN-SN-42',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 340,
        totalPrice: 340,
      },
      {
        id: 'line-2',
        productId: 'prod-sports-socks',
        productName: 'Sports Socks (3-pack)',
        sku: 'SPS-3PK-WHT',
        image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 45,
        totalPrice: 45,
      },
    ],
    productsCount: 2,
    subtotal: 385,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 405,
    paymentStatus: 'paid',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-771204',
    orderStatus: 'ready_for_shipment',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '5 Spintex Road, Baatsona',
      region: 'Greater Accra',
      city: 'Tema',
      notes: 'Leave with security if unavailable.',
    },
  },
  {
    id: 'ORD-1045',
    orderNumber: 'ORD-1045',
    orderDate: '2026-06-15T09:15:00',
    customer: {
      name: 'Yaw Osei',
      email: 'yaw.osei@example.com',
      phone: '+233 27 321 0987',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-portable-blender',
        productName: 'Portable Blender',
        sku: 'PBL-600',
        image: 'https://images.unsplash.com/photo-1570222094114-792a308585bc?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 360,
        totalPrice: 360,
      },
    ],
    productsCount: 1,
    subtotal: 360,
    deliveryFee: 15,
    discount: 15,
    totalAmount: 360,
    paymentStatus: 'paid',
    paymentMethod: 'Bank Transfer',
    transactionReference: 'TXN-BANK-330118',
    orderStatus: 'shipped',
    deliveryMethod: 'Pickup',
    delivery: {
      address: 'Vendor pickup point — Accra Mall',
      region: 'Greater Accra',
      city: 'Accra',
      notes: 'Customer will collect after 5 PM.',
    },
  },
  {
    id: 'ORD-1044',
    orderNumber: 'ORD-1044',
    orderDate: '2026-06-14T16:30:00',
    customer: {
      name: 'Abena Kwarteng',
      email: 'abena.k@example.com',
      phone: '+233 50 112 2334',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-desk-lamp',
        productName: 'Desk LED Lamp',
        sku: 'LED-DESK-01',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 240,
        totalPrice: 240,
      },
    ],
    productsCount: 1,
    subtotal: 240,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 260,
    paymentStatus: 'paid',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-229871',
    orderStatus: 'delivered',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '8 Oxford Street, Osu',
      region: 'Greater Accra',
      city: 'Accra',
      notes: '',
    },
  },
  {
    id: 'ORD-1043',
    orderNumber: 'ORD-1043',
    orderDate: '2026-06-13T08:50:00',
    customer: {
      name: 'Kofi Annan Jr.',
      email: 'kofi.a@example.com',
      phone: '+233 26 778 9900',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-usb-hub',
        productName: 'USB-C Hub 7-in-1',
        sku: 'HUB-7IN1-GRY',
        image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 185,
        totalPrice: 185,
      },
    ],
    productsCount: 1,
    subtotal: 185,
    deliveryFee: 15,
    discount: 0,
    totalAmount: 200,
    paymentStatus: 'refunded',
    paymentMethod: 'Card',
    transactionReference: 'TXN-CARD-118004',
    orderStatus: 'refunded',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '33 Liberation Road',
      region: 'Central',
      city: 'Cape Coast',
      notes: 'Refund processed — item returned.',
    },
  },
  {
    id: 'ORD-1042',
    orderNumber: 'ORD-1042',
    orderDate: '2026-06-12T20:10:00',
    customer: {
      name: 'Selorm Agbeko',
      email: 'selorm.a@example.com',
      phone: '+233 54 667 8899',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-bluetooth-speaker',
        productName: 'Bluetooth Speaker Mini',
        sku: 'SPK-MINI-BLU',
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 220,
        totalPrice: 220,
      },
    ],
    productsCount: 1,
    subtotal: 220,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 240,
    paymentStatus: 'pending',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-PENDING-004',
    orderStatus: 'pending',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '12 Airport Residential Area',
      region: 'Greater Accra',
      city: 'Accra',
      notes: '',
    },
  },
  {
    id: 'ORD-1041',
    orderNumber: 'ORD-1041',
    orderDate: '2026-06-12T13:45:00',
    customer: {
      name: 'Naomi Tetteh',
      email: 'naomi.t@example.com',
      phone: '+233 24 900 1122',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-coffee-mug',
        productName: 'Ceramic Coffee Mug Set',
        sku: 'MUG-SET-4',
        image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca1d?w=120&h=120&fit=crop',
        quantity: 2,
        unitPrice: 95,
        totalPrice: 190,
      },
    ],
    productsCount: 2,
    subtotal: 190,
    deliveryFee: 18,
    discount: 0,
    totalAmount: 208,
    paymentStatus: 'failed',
    paymentMethod: 'Card',
    transactionReference: 'TXN-CARD-FAIL-991',
    orderStatus: 'pending',
    deliveryMethod: 'Express Delivery',
    delivery: {
      address: '7 Labadi Beach Road',
      region: 'Greater Accra',
      city: 'Accra',
      notes: 'Payment retry requested.',
    },
  },
  {
    id: 'ORD-1040',
    orderNumber: 'ORD-1040',
    orderDate: '2026-06-11T10:20:00',
    customer: {
      name: 'Daniel Asare',
      email: 'daniel.asare@example.com',
      phone: '+233 55 443 2211',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-laptop-stand',
        productName: 'Laptop Stand Aluminium',
        sku: 'LPS-ALU-SLV',
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 175,
        totalPrice: 175,
      },
      {
        id: 'line-2',
        productId: 'prod-wireless-mouse',
        productName: 'Wireless Mouse',
        sku: 'MSE-WL-BLK',
        image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 85,
        totalPrice: 85,
      },
    ],
    productsCount: 2,
    subtotal: 260,
    deliveryFee: 22,
    discount: 10,
    totalAmount: 272,
    paymentStatus: 'paid',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-660331',
    orderStatus: 'processing',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '19 Sunyani Road',
      region: 'Bono',
      city: 'Sunyani',
      notes: '',
    },
  },
  {
    id: 'ORD-1039',
    orderNumber: 'ORD-1039',
    orderDate: '2026-06-10T15:55:00',
    customer: {
      name: 'Grace Ofori',
      email: 'grace.ofori@example.com',
      phone: '+233 20 334 5566',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-yoga-mat',
        productName: 'Yoga Mat Premium',
        sku: 'YGA-MAT-PRP',
        image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=120&h=120&fit=crop',
        quantity: 1,
        unitPrice: 130,
        totalPrice: 130,
      },
    ],
    productsCount: 1,
    subtotal: 130,
    deliveryFee: 18,
    discount: 0,
    totalAmount: 148,
    paymentStatus: 'paid',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-550019',
    orderStatus: 'shipped',
    deliveryMethod: 'Standard Delivery',
    delivery: {
      address: '3 Tamale High Street',
      region: 'Northern',
      city: 'Tamale',
      notes: 'Fragile — handle with care.',
    },
  },
  {
    id: 'ORD-1038',
    orderNumber: 'ORD-1038',
    orderDate: '2026-06-09T09:30:00',
    customer: {
      name: 'Michael Tagoe',
      email: 'michael.t@example.com',
      phone: '+233 27 880 4411',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-water-bottle',
        productName: 'Stainless Steel Water Bottle',
        sku: 'BTL-SS-750',
        image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=120&h=120&fit=crop',
        quantity: 3,
        unitPrice: 55,
        totalPrice: 165,
      },
    ],
    productsCount: 3,
    subtotal: 165,
    deliveryFee: 15,
    discount: 0,
    totalAmount: 180,
    paymentStatus: 'paid',
    paymentMethod: 'Bank Transfer',
    transactionReference: 'TXN-BANK-440012',
    orderStatus: 'delivered',
    deliveryMethod: 'Pickup',
    delivery: {
      address: 'Vendor pickup point — Kumasi City Mall',
      region: 'Ashanti',
      city: 'Kumasi',
      notes: '',
    },
  },
  {
    id: 'ORD-1037',
    orderNumber: 'ORD-1037',
    orderDate: '2026-06-08T17:15:00',
    customer: {
      name: 'Patience Nyarko',
      email: 'patience.n@example.com',
      phone: '+233 50 221 3344',
    },
    items: [
      {
        id: 'line-1',
        productId: 'prod-phone-case',
        productName: 'Phone Case — iPhone 15',
        sku: 'PHC-IP15-CLR',
        image: 'https://images.unsplash.com/photo-1601784551445-20e9ef9a3d2d?w=120&h=120&fit=crop',
        quantity: 2,
        unitPrice: 35,
        totalPrice: 70,
      },
      {
        id: 'line-2',
        productId: 'prod-screen-protector',
        productName: 'Screen Protector Glass',
        sku: 'SCR-IP15-GLS',
        image: 'https://images.unsplash.com/photo-1585790050230-5dd284e3ff95?w=120&h=120&fit=crop',
        quantity: 2,
        unitPrice: 25,
        totalPrice: 50,
      },
    ],
    productsCount: 4,
    subtotal: 120,
    deliveryFee: 12,
    discount: 0,
    totalAmount: 132,
    paymentStatus: 'paid',
    paymentMethod: 'Mobile Money',
    transactionReference: 'TXN-MOMO-330007',
    orderStatus: 'ready_for_shipment',
    deliveryMethod: 'Express Delivery',
    delivery: {
      address: '45 Ho Municipal Road',
      region: 'Volta',
      city: 'Ho',
      notes: '',
    },
  },
]

export const RECENT_ORDERS = MOCK_VENDOR_ORDERS.slice(0, 6).map(toRecentOrderPreview)

export function getOrderById(orderId) {
  return MOCK_VENDOR_ORDERS.find((order) => order.id === orderId) ?? null
}
