/** Default empty catalog — replace with API data when available */
export const MOCK_VENDOR_REVIEWS = []

export const MOCK_REVIEWS_SUMMARY_PREVIOUS = {
  averageRating: 0,
  totalReviews: 0,
  pendingReplies: 0,
  responseRate: 0,
}

/** Dev-only sample data for UI testing */
export const DEV_VENDOR_REVIEWS = [
  {
    id: 'rev-001',
    productId: 'prod-web-earbuds',
    productName: 'Wireless Earbuds Pro',
    productImage: 'https://images.unsplash.com/photo-1590658268037-6bf3f7f2b8fd?w=120&h=120&fit=crop',
    customerId: 'cust-ama-mensah',
    customerName: 'Ama Mensah',
    orderId: 'ORD-1048',
    orderNumber: 'ORD-1048',
    rating: 5,
    title: 'Absolutely love these!',
    comment: 'Fast delivery and the earbuds work perfectly. Sound quality is crisp, battery lasts all day, and they pair instantly with my phone. Will definitely order again from this store.',
    date: '2026-06-17T10:00:00Z',
    helpfulCount: 12,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Thank you so much, Ama! We\'re thrilled the earbuds exceeded your expectations. See you again soon!',
      date: '2026-06-17T15:30:00Z',
    },
  },
  {
    id: 'rev-002',
    productId: 'prod-running-shoes',
    productName: 'Men\'s Running Shoes',
    productImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&h=120&fit=crop',
    customerId: 'cust-efua-adjei',
    customerName: 'Efua Adjei',
    orderId: 'ORD-1046',
    orderNumber: 'ORD-1046',
    rating: 4,
    title: 'Great fit, minor packaging issue',
    comment: 'Sneakers fit well and are very comfortable for daily runs. Packaging could be sturdier — the box arrived slightly dented, though the shoes were fine.',
    date: '2026-06-16T09:30:00Z',
    helpfulCount: 8,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-003',
    productId: 'prod-desk-lamp',
    productName: 'LED Desk Lamp',
    productImage: 'https://images.unsplash.com/photo-1507473889455-b7bdd458ad14?w=120&h=120&fit=crop',
    customerId: 'cust-abena-k',
    customerName: 'Abena K.',
    orderId: 'ORD-1044',
    orderNumber: 'ORD-1044',
    rating: 5,
    title: 'Perfect for my home office',
    comment: 'Desk lamp arrived in great condition. Adjustable brightness is a nice touch. Very happy with the purchase and the warm light tone.',
    date: '2026-06-15T14:20:00Z',
    helpfulCount: 5,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Thanks Abena! Glad the lamp is working well for your workspace.',
      date: '2026-06-15T18:00:00Z',
    },
  },
  {
    id: 'rev-004',
    productId: 'prod-blender-set',
    productName: 'Kitchen Blender Set',
    productImage: 'https://images.unsplash.com/photo-1570226196312-aaafbd2a6e09?w=120&h=120&fit=crop',
    customerId: 'cust-daniel-asare',
    customerName: 'Daniel Asare',
    orderId: 'ORD-1040',
    orderNumber: 'ORD-1040',
    rating: 3,
    title: 'Decent product, slow delivery',
    comment: 'Products are good but delivery took longer than expected. Blender works fine for smoothies. Would appreciate faster shipping next time.',
    date: '2026-06-12T11:45:00Z',
    helpfulCount: 3,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-005',
    productId: 'prod-galaxy-a15',
    productName: 'Samsung Galaxy A15',
    productImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=120&h=120&fit=crop',
    customerId: 'cust-kwame-osei',
    customerName: 'Kwame Osei',
    orderId: 'ORD-10482',
    orderNumber: 'ORD-10482',
    rating: 5,
    title: 'Excellent value for money',
    comment: 'Bought two units for my siblings. Both phones arrived sealed, genuine, and fully functional. Camera quality is impressive at this price point.',
    date: '2026-03-18T16:00:00Z',
    helpfulCount: 24,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Kwame, thank you for the kind words! We always ensure genuine products. Enjoy the new phones!',
      date: '2026-03-19T09:15:00Z',
    },
  },
  {
    id: 'rev-006',
    productId: 'prod-hp-laptop',
    productName: 'HP Laptop 15s',
    productImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=120&h=120&fit=crop',
    customerId: 'cust-yaa-boateng',
    customerName: 'Yaa Boateng',
    orderId: 'ORD-10459',
    orderNumber: 'ORD-10459',
    rating: 4,
    title: 'Solid laptop for work',
    comment: 'Handles Microsoft Office and video calls smoothly. Slightly heavier than I expected but build quality is good. Charger included as described.',
    date: '2026-03-11T12:30:00Z',
    helpfulCount: 11,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-007',
    productId: 'prod-smart-watch',
    productName: 'Smart Watch Series 8',
    productImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=120&h=120&fit=crop',
    customerId: 'cust-kofi-mensah',
    customerName: 'Kofi Mensah',
    orderId: 'ORD-10408',
    orderNumber: 'ORD-10408',
    rating: 2,
    title: 'Battery life disappointing',
    comment: 'Watch looks great but battery barely lasts a full day with normal use. Expected better based on the product description. Considering a return.',
    date: '2026-03-02T17:00:00Z',
    helpfulCount: 7,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-008',
    productId: 'prod-gaming-mouse',
    productName: 'Gaming Mouse RGB',
    productImage: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=120&h=120&fit=crop',
    customerId: 'cust-akosua-frimpong',
    customerName: 'Akosua Frimpong',
    orderId: 'ORD-10365',
    orderNumber: 'ORD-10365',
    rating: 5,
    title: 'Best mouse I\'ve owned',
    comment: 'Responsive, comfortable grip, and the RGB lighting is subtle but nice. Perfect for both gaming and everyday use. Highly recommend!',
    date: '2026-02-22T11:20:00Z',
    helpfulCount: 15,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Akosua, we appreciate the recommendation! Happy gaming!',
      date: '2026-02-22T16:45:00Z',
    },
  },
  {
    id: 'rev-009',
    productId: 'prod-office-chair',
    productName: 'Office Desk Chair',
    productImage: 'https://images.unsplash.com/photo-1580480051063-6cf5f6f9f8f8?w=120&h=120&fit=crop',
    customerId: 'cust-nana-yaw',
    customerName: 'Nana Yaw',
    orderId: 'ORD-10395',
    orderNumber: 'ORD-10395',
    rating: 4,
    title: 'Comfortable for long hours',
    comment: 'Good lumbar support and easy assembly. Took about 20 minutes to put together. Wheels roll smoothly on my tile floor.',
    date: '2026-02-28T14:45:00Z',
    helpfulCount: 6,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-010',
    productId: 'prod-bluetooth-speaker',
    productName: 'Bluetooth Speaker Mini',
    productImage: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=120&h=120&fit=crop',
    customerId: 'cust-adjoa-sarpong',
    customerName: 'Adjoa Sarpong',
    orderId: 'ORD-10388',
    orderNumber: 'ORD-10388',
    rating: 5,
    title: 'Punchy sound for the size',
    comment: 'Tiny but mighty! Takes everywhere — beach, kitchen, shower. IPX rating seems legit. Already ordered a second one as a gift.',
    date: '2026-02-26T16:10:00Z',
    helpfulCount: 9,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Thank you Adjoa! Glad you love it enough to gift one too!',
      date: '2026-02-27T10:00:00Z',
    },
  },
  {
    id: 'rev-011',
    productId: 'prod-iphone-case',
    productName: 'iPhone 13 Case (Bundle)',
    productImage: 'https://images.unsplash.com/photo-1601784551445-20c9a07cdbdb?w=120&h=120&fit=crop',
    customerId: 'cust-michael-addo',
    customerName: 'Michael Addo',
    orderId: 'ORD-10428',
    orderNumber: 'ORD-10428',
    rating: 3,
    title: 'Cases are fine, colours differ slightly',
    comment: 'Bundle is good value. One of the cases had a slightly different shade of blue than shown in the photo. Still usable though.',
    date: '2026-03-05T15:00:00Z',
    helpfulCount: 2,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-012',
    productId: 'prod-web-earbuds',
    productName: 'Wireless Earbuds Pro',
    productImage: 'https://images.unsplash.com/photo-1590658268037-6bf3f7f2b8fd?w=120&h=120&fit=crop',
    customerId: 'cust-grace-ampofo',
    customerName: 'Grace Ampofo',
    orderId: 'ORD-10471',
    orderNumber: 'ORD-10471',
    rating: 4,
    title: 'Good ANC for the price',
    comment: 'Noise cancellation works well on the trotro. Case is compact. Only wish the touch controls were a bit more responsive.',
    date: '2026-03-14T09:00:00Z',
    helpfulCount: 4,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-013',
    productId: 'prod-galaxy-a15',
    productName: 'Samsung Galaxy A15',
    productImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=120&h=120&fit=crop',
    customerId: 'cust-emmanuel-tetteh',
    customerName: 'Emmanuel Tetteh',
    orderId: 'ORD-10452',
    orderNumber: 'ORD-10452',
    rating: 1,
    title: 'Received wrong colour',
    comment: 'Ordered midnight black, received blue. Have contacted support twice with no resolution yet. Very frustrated with this experience.',
    date: '2026-03-10T08:30:00Z',
    helpfulCount: 1,
    isVerifiedPurchase: true,
    status: 'hidden',
    vendorReply: null,
  },
  {
    id: 'rev-014',
    productId: 'prod-running-shoes',
    productName: 'Men\'s Running Shoes',
    productImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&h=120&fit=crop',
    customerId: 'cust-naa-oduro',
    customerName: 'Naa Oduro',
    orderId: 'ORD-10441',
    orderNumber: 'ORD-10441',
    rating: 5,
    title: 'Marathon ready!',
    comment: 'Wore these for the Accra Marathon prep — zero blisters, excellent cushioning. True to size. These are keepers.',
    date: '2026-03-08T13:15:00Z',
    helpfulCount: 18,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Naa, congrats on the marathon prep! Rooting for you on race day!',
      date: '2026-03-08T19:00:00Z',
    },
  },
  {
    id: 'rev-015',
    productId: 'prod-hp-laptop',
    productName: 'HP Laptop 15s',
    productImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=120&h=120&fit=crop',
    customerId: 'cust-paa-kwesi',
    customerName: 'Paa Kwesi',
    orderId: 'ORD-10372',
    orderNumber: 'ORD-10372',
    rating: 2,
    title: 'Fan noise is too loud',
    comment: 'Performance is okay for basic tasks but the fan kicks in loudly even when just browsing. Expected quieter operation for the price paid.',
    date: '2026-02-24T10:00:00Z',
    helpfulCount: 5,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-016',
    productId: 'prod-blender-set',
    productName: 'Kitchen Blender Set',
    productImage: 'https://images.unsplash.com/photo-1570226196312-aaafbd2a6e09?w=120&h=120&fit=crop',
    customerId: 'cust-efua-mensah',
    customerName: 'Efua Mensah',
    orderId: 'ORD-10465',
    orderNumber: 'ORD-10465',
    rating: 5,
    title: 'Makes the best smoothies',
    comment: 'Powerful motor crushes ice effortlessly. All attachments included as listed. Cleaning is easy — just rinse under the tap.',
    date: '2026-03-12T07:45:00Z',
    helpfulCount: 7,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-017',
    productId: 'prod-smart-watch',
    productName: 'Smart Watch Series 8',
    productImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=120&h=120&fit=crop',
    customerId: 'cust-kojo-anang',
    customerName: 'Kojo Anang',
    orderId: 'ORD-10415',
    orderNumber: 'ORD-10415',
    rating: 4,
    title: 'Great fitness tracker',
    comment: 'Step counting and heart rate monitor are accurate. App sync is seamless. Strap could be more premium feeling.',
    date: '2026-03-03T11:30:00Z',
    helpfulCount: 3,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: {
      text: 'Thanks Kojo! We\'ll pass the strap feedback to our team.',
      date: '2026-03-03T16:20:00Z',
    },
  },
  {
    id: 'rev-018',
    productId: 'prod-desk-lamp',
    productName: 'LED Desk Lamp',
    productImage: 'https://images.unsplash.com/photo-1507473889455-b7bdd458ad14?w=120&h=120&fit=crop',
    customerId: 'cust-ama-darko',
    customerName: 'Ama Darko',
    orderId: 'ORD-10419',
    orderNumber: 'ORD-10419',
    rating: 5,
    title: 'Elegant design',
    comment: 'Looks premium on my desk. USB charging port on the base is a thoughtful bonus. Dimming works smoothly without flicker.',
    date: '2026-03-04T12:00:00Z',
    helpfulCount: 4,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
  {
    id: 'rev-019',
    productId: 'prod-gaming-mouse',
    productName: 'Gaming Mouse RGB',
    productImage: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=120&h=120&fit=crop',
    customerId: 'cust-samuel-owusu',
    customerName: 'Samuel Owusu',
    orderId: 'ORD-10458',
    orderNumber: 'ORD-10458',
    rating: 1,
    title: 'Stopped working after a week',
    comment: 'Left click started double-clicking after just 7 days. Build felt cheap from the start. Requesting full refund.',
    date: '2026-03-13T20:00:00Z',
    helpfulCount: 2,
    isVerifiedPurchase: true,
    status: 'hidden',
    vendorReply: null,
  },
  {
    id: 'rev-020',
    productId: 'prod-bluetooth-speaker',
    productName: 'Bluetooth Speaker Mini',
    productImage: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=120&h=120&fit=crop',
    customerId: 'cust-linda-agyeman',
    customerName: 'Linda Agyeman',
    orderId: 'ORD-10428',
    orderNumber: 'ORD-10428',
    rating: 4,
    title: 'Great for outdoor picnics',
    comment: 'Loud enough for a group of 6 outdoors. Connects quickly via Bluetooth 5.0. Would give 5 stars if it had a carrying strap.',
    date: '2026-03-05T18:30:00Z',
    helpfulCount: 6,
    isVerifiedPurchase: true,
    status: 'published',
    vendorReply: null,
  },
]

export const DEV_REVIEWS_SUMMARY_PREVIOUS = {
  averageRating: 4.1,
  totalReviews: 142,
  pendingReplies: 18,
  responseRate: 72,
}
