export const categoryMenuItems = [
  {
    id: 'computer-laptop',
    label: 'Computer & Laptop',
    href: '/categories/computer-laptop',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/computer-laptop' },
      { id: 'laptops', label: 'Laptops', href: '/categories/computer-laptop/laptops' },
      { id: 'desktops', label: 'Desktops', href: '/categories/computer-laptop/desktops' },
      { id: 'macbook', label: 'MacBook', href: '/categories/computer-laptop/macbook' },
      { id: 'gaming-pcs', label: 'Gaming PCs', href: '/categories/computer-laptop/gaming-pcs' },
    ],
    featuredTitle: 'FEATURED LAPTOPS',
    featured: [
      {
        id: 'laptop-1',
        name: 'MacBook Air M3',
        price: 1299,
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=120&h=120&fit=crop',
        href: '/products/macbook-air-m3',
      },
      {
        id: 'laptop-2',
        name: 'Dell XPS 15',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=120&h=120&fit=crop',
        href: '/products/dell-xps-15',
      },
      {
        id: 'laptop-3',
        name: 'ASUS ROG Zephyrus',
        price: 1899,
        compareAt: 2199,
        image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=120&h=120&fit=crop',
        href: '/products/asus-rog-zephyrus',
      },
    ],
    promo: {
      discount: '15% Discount',
      headline: 'Power through your workflow with premium ultrabooks built for speed.',
      productName: 'Ultrabook Collection',
      priceLabel: 'Starting price:',
      price: 899,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=280&h=200&fit=crop',
      href: '/categories/computer-laptop',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'computer-accessories',
    label: 'Computer Accessories',
    href: '/categories/computer-accessories',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/computer-accessories' },
      { id: 'keyboards', label: 'Keyboards', href: '/categories/computer-accessories/keyboards' },
      { id: 'mice', label: 'Mice', href: '/categories/computer-accessories/mice' },
      { id: 'monitors', label: 'Monitors', href: '/categories/computer-accessories/monitors' },
      { id: 'docks', label: 'Docking Stations', href: '/categories/computer-accessories/docks' },
    ],
    featuredTitle: 'FEATURED ACCESSORIES',
    featured: [
      {
        id: 'acc-1',
        name: 'Mechanical Keyboard Pro',
        price: 129,
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=120&h=120&fit=crop',
        href: '/products/mechanical-keyboard-pro',
      },
      {
        id: 'acc-2',
        name: 'Wireless Mouse Elite',
        price: 79,
        image: 'https://images.unsplash.com/photo-1527864551657-593967aef8b8?w=120&h=120&fit=crop',
        href: '/products/wireless-mouse-elite',
      },
      {
        id: 'acc-3',
        name: '4K UltraWide Monitor',
        price: 549,
        compareAt: 649,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=120&h=120&fit=crop',
        href: '/products/4k-ultrawide-monitor',
      },
    ],
    promo: {
      discount: 'Bundle & Save',
      headline: 'Complete your desk setup with curated accessory bundles.',
      productName: 'Desk Essentials Kit',
      priceLabel: 'Starting price:',
      price: 199,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1593640408188-3a526e038b98?w=280&h=200&fit=crop',
      href: '/categories/computer-accessories',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'smartphone',
    label: 'SmartPhone',
    href: '/categories/smartphone',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/smartphone' },
      { id: 'iphone', label: 'iPhone', href: '/categories/smartphone/iphone' },
      { id: 'samsung', label: 'Samsung', href: '/categories/smartphone/samsung' },
      { id: 'realme', label: 'Realme', href: '/categories/smartphone/realme' },
      { id: 'xiaomi', label: 'Xiaomi', href: '/categories/smartphone/xiaomi' },
      { id: 'oppo', label: 'Oppo', href: '/categories/smartphone/oppo' },
      { id: 'vivo', label: 'Vivo', href: '/categories/smartphone/vivo' },
      { id: 'oneplus', label: 'OnePlus', href: '/categories/smartphone/oneplus' },
      { id: 'huawei', label: 'Huawei', href: '/categories/smartphone/huawei' },
      { id: 'infinix', label: 'Infinix', href: '/categories/smartphone/infinix' },
      { id: 'tecno', label: 'Tecno', href: '/categories/smartphone/tecno' },
    ],
    featuredTitle: 'FEATURED PHONES',
    featured: [
      {
        id: 'phone-1',
        name: 'FEEBO 128GB',
        price: 900,
        image: 'https://images.unsplash.com/photo-1598327105666-5b1731f7e1b6?w=120&h=120&fit=crop',
        href: '/products/feebo-128gb',
      },
      {
        id: 'phone-2',
        name: 'FEEBO 128GB',
        price: 900,
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=120&h=120&fit=crop',
        href: '/products/feebo-128gb-v2',
      },
      {
        id: 'phone-3',
        name: 'Samsung S22 Ultra',
        price: 2300,
        compareAt: 3200,
        image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=120&h=120&fit=crop',
        href: '/products/samsung-s22-ultra',
      },
    ],
    promo: {
      discount: '21% Discount',
      headline: "Escape the noise, It's time to hear the magic with Xiaomi Earbuds.",
      productName: 'Xiaomi Earbuds',
      priceLabel: 'Starting price:',
      price: 99,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=280&h=200&fit=crop',
      href: '/categories/smartphone/xiaomi',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'headphone',
    label: 'Headphone',
    href: '/categories/headphone',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/headphone' },
      { id: 'over-ear', label: 'Over-Ear', href: '/categories/headphone/over-ear' },
      { id: 'in-ear', label: 'In-Ear', href: '/categories/headphone/in-ear' },
      { id: 'wireless', label: 'Wireless', href: '/categories/headphone/wireless' },
      { id: 'noise-cancelling', label: 'Noise Cancelling', href: '/categories/headphone/noise-cancelling' },
    ],
    featuredTitle: 'FEATURED AUDIO',
    featured: [
      {
        id: 'hp-1',
        name: 'Studio Pro Max',
        price: 349,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=120&h=120&fit=crop',
        href: '/products/studio-pro-max',
      },
      {
        id: 'hp-2',
        name: 'AirPods Pro 2',
        price: 249,
        image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=120&h=120&fit=crop',
        href: '/products/airpods-pro-2',
      },
      {
        id: 'hp-3',
        name: 'Sony WH-1000XM5',
        price: 399,
        compareAt: 449,
        image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=120&h=120&fit=crop',
        href: '/products/sony-wh-1000xm5',
      },
    ],
    promo: {
      discount: '18% Discount',
      headline: 'Immerse yourself in studio-grade sound with our top picks.',
      productName: 'Premium Audio Picks',
      priceLabel: 'Starting price:',
      price: 79,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=280&h=200&fit=crop',
      href: '/categories/headphone',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'mobile-accessories',
    label: 'Mobile Accessories',
    href: '/categories/mobile-accessories',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/mobile-accessories' },
      { id: 'cases', label: 'Cases', href: '/categories/mobile-accessories/cases' },
      { id: 'chargers', label: 'Chargers', href: '/categories/mobile-accessories/chargers' },
      { id: 'power-banks', label: 'Power Banks', href: '/categories/mobile-accessories/power-banks' },
    ],
    featuredTitle: 'TOP ACCESSORIES',
    featured: [
      {
        id: 'ma-1',
        name: 'MagSafe Case Pro',
        price: 45,
        image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=120&h=120&fit=crop',
        href: '/products/magsafe-case-pro',
      },
      {
        id: 'ma-2',
        name: '65W GaN Charger',
        price: 59,
        image: 'https://images.unsplash.com/photo-1583863788437-eb148a2a5803?w=120&h=120&fit=crop',
        href: '/products/65w-gan-charger',
      },
      {
        id: 'ma-3',
        name: '20,000mAh Power Bank',
        price: 89,
        compareAt: 109,
        image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=120&h=120&fit=crop',
        href: '/products/20000mah-power-bank',
      },
    ],
    promo: {
      discount: '25% Off',
      headline: 'Protect and power your phone with essentials that last.',
      productName: 'Mobile Essentials',
      priceLabel: 'Starting price:',
      price: 29,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=280&h=200&fit=crop',
      href: '/categories/mobile-accessories',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'gaming-console',
    label: 'Gaming Console',
    href: '/categories/gaming-console',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/gaming-console' },
      { id: 'playstation', label: 'PlayStation', href: '/categories/gaming-console/playstation' },
      { id: 'xbox', label: 'Xbox', href: '/categories/gaming-console/xbox' },
      { id: 'nintendo', label: 'Nintendo', href: '/categories/gaming-console/nintendo' },
    ],
    featuredTitle: 'FEATURED GAMING',
    featured: [
      {
        id: 'gc-1',
        name: 'PlayStation 5',
        price: 499,
        image: 'https://images.unsplash.com/photo-1606814894317-8c7e0a4a2a2a?w=120&h=120&fit=crop',
        href: '/products/playstation-5',
      },
      {
        id: 'gc-2',
        name: 'Xbox Series X',
        price: 499,
        image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=120&h=120&fit=crop',
        href: '/products/xbox-series-x',
      },
      {
        id: 'gc-3',
        name: 'Nintendo Switch OLED',
        price: 349,
        compareAt: 399,
        image: 'https://images.unsplash.com/photo-1578303512597-81e934cc8893?w=120&h=120&fit=crop',
        href: '/products/nintendo-switch-oled',
      },
    ],
    promo: {
      discount: 'Hot Deal',
      headline: 'Level up your setup with consoles and exclusive bundles.',
      productName: 'Gaming Bundles',
      priceLabel: 'Starting price:',
      price: 449,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=280&h=200&fit=crop',
      href: '/categories/gaming-console',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'camera-photo',
    label: 'Camera & Photo',
    href: '/categories/camera-photo',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/camera-photo' },
      { id: 'dslr', label: 'DSLR', href: '/categories/camera-photo/dslr' },
      { id: 'mirrorless', label: 'Mirrorless', href: '/categories/camera-photo/mirrorless' },
      { id: 'action', label: 'Action Cameras', href: '/categories/camera-photo/action' },
    ],
    featuredTitle: 'FEATURED CAMERAS',
    featured: [
      {
        id: 'cam-1',
        name: 'Canon EOS R6',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=120&h=120&fit=crop',
        href: '/products/canon-eos-r6',
      },
      {
        id: 'cam-2',
        name: 'Sony Alpha A7 IV',
        price: 2498,
        image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=120&h=120&fit=crop',
        href: '/products/sony-alpha-a7-iv',
      },
      {
        id: 'cam-3',
        name: 'GoPro Hero 12',
        price: 399,
        compareAt: 449,
        image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=120&h=120&fit=crop',
        href: '/products/gopro-hero-12',
      },
    ],
    promo: {
      discount: '12% Discount',
      headline: 'Capture every moment with pro-grade cameras and lenses.',
      productName: 'Creator Kits',
      priceLabel: 'Starting price:',
      price: 299,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=280&h=200&fit=crop',
      href: '/categories/camera-photo',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'tv-appliances',
    label: 'TV & Homes Appliances',
    href: '/categories/tv-appliances',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/tv-appliances' },
      { id: 'smart-tv', label: 'Smart TV', href: '/categories/tv-appliances/smart-tv' },
      { id: 'refrigerators', label: 'Refrigerators', href: '/categories/tv-appliances/refrigerators' },
      { id: 'washers', label: 'Washers', href: '/categories/tv-appliances/washers' },
    ],
    featuredTitle: 'FEATURED HOME',
    featured: [
      {
        id: 'tv-1',
        name: 'Samsung 65" OLED',
        price: 1799,
        image: 'https://images.unsplash.com/photo-1593359673501-4d4d1a1a1a1a?w=120&h=120&fit=crop',
        href: '/products/samsung-65-oled',
      },
      {
        id: 'tv-2',
        name: 'LG Smart Fridge',
        price: 2199,
        image: 'https://images.unsplash.com/photo-1571175443880-49f1c25f2e2e?w=120&h=120&fit=crop',
        href: '/products/lg-smart-fridge',
      },
      {
        id: 'tv-3',
        name: 'Sony Bravia XR',
        price: 1499,
        compareAt: 1699,
        image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=120&h=120&fit=crop',
        href: '/products/sony-bravia-xr',
      },
    ],
    promo: {
      discount: 'Free Delivery',
      headline: 'Upgrade your living space with smart home essentials.',
      productName: 'Smart Home Deals',
      priceLabel: 'Starting price:',
      price: 599,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=280&h=200&fit=crop',
      href: '/categories/tv-appliances',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'watches',
    label: 'Watches & Accessories',
    href: '/categories/watches',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/watches' },
      { id: 'smartwatches', label: 'Smartwatches', href: '/categories/watches/smartwatches' },
      { id: 'fitness', label: 'Fitness Bands', href: '/categories/watches/fitness' },
      { id: 'straps', label: 'Straps', href: '/categories/watches/straps' },
    ],
    featuredTitle: 'FEATURED WEARABLES',
    featured: [
      {
        id: 'watch-1',
        name: 'Apple Watch Ultra 2',
        price: 799,
        image: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=120&h=120&fit=crop',
        href: '/products/apple-watch-ultra-2',
      },
      {
        id: 'watch-2',
        name: 'Galaxy Watch 6',
        price: 329,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=120&h=120&fit=crop',
        href: '/products/galaxy-watch-6',
      },
      {
        id: 'watch-3',
        name: 'Garmin Fenix 7',
        price: 699,
        compareAt: 799,
        image: 'https://images.unsplash.com/photo-1544117519-31a4b719223e?w=120&h=120&fit=crop',
        href: '/products/garmin-fenix-7',
      },
    ],
    promo: {
      discount: '10% Off',
      headline: 'Track fitness, stay connected, and look sharp on your wrist.',
      productName: 'Wearable Picks',
      priceLabel: 'Starting price:',
      price: 149,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=280&h=200&fit=crop',
      href: '/categories/watches',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'gps-navigation',
    label: 'GPS & Navigation',
    href: '/categories/gps-navigation',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/gps-navigation' },
      { id: 'car-gps', label: 'Car GPS', href: '/categories/gps-navigation/car-gps' },
      { id: 'handheld', label: 'Handheld', href: '/categories/gps-navigation/handheld' },
    ],
    featuredTitle: 'FEATURED GPS',
    featured: [
      {
        id: 'gps-1',
        name: 'Garmin DriveSmart 65',
        price: 249,
        image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=120&h=120&fit=crop',
        href: '/products/garmin-drivesmart-65',
      },
      {
        id: 'gps-2',
        name: 'TomTom Go Discover',
        price: 279,
        image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=120&h=120&fit=crop',
        href: '/products/tomtom-go-discover',
      },
      {
        id: 'gps-3',
        name: 'Garmin eTrex 32x',
        price: 299,
        compareAt: 349,
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=120&h=120&fit=crop',
        href: '/products/garmin-etrex-32x',
      },
    ],
    promo: {
      discount: 'Road Ready',
      headline: 'Never lose your way with reliable navigation for every journey.',
      productName: 'Navigation Deals',
      priceLabel: 'Starting price:',
      price: 129,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1449965405229-596af4955784?w=280&h=200&fit=crop',
      href: '/categories/gps-navigation',
      cta: 'SHOP NOW',
    },
  },
  {
    id: 'wearable-tech',
    label: 'Wearable Technology',
    href: '/categories/wearable-tech',
    subcategories: [
      { id: 'all', label: 'All', href: '/categories/wearable-tech' },
      { id: 'vr', label: 'VR Headsets', href: '/categories/wearable-tech/vr' },
      { id: 'ar', label: 'AR Glasses', href: '/categories/wearable-tech/ar' },
      { id: 'trackers', label: 'Health Trackers', href: '/categories/wearable-tech/trackers' },
    ],
    featuredTitle: 'FEATURED WEARABLES',
    featured: [
      {
        id: 'wt-1',
        name: 'Meta Quest 3',
        price: 499,
        image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=120&h=120&fit=crop',
        href: '/products/meta-quest-3',
      },
      {
        id: 'wt-2',
        name: 'Oura Ring Gen 3',
        price: 299,
        image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=120&h=120&fit=crop',
        href: '/products/oura-ring-gen-3',
      },
      {
        id: 'wt-3',
        name: 'Ray-Ban Meta',
        price: 329,
        compareAt: 379,
        image: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=120&h=120&fit=crop',
        href: '/products/ray-ban-meta',
      },
    ],
    promo: {
      discount: 'Future Tech',
      headline: 'Experience the next generation of wearable innovation.',
      productName: 'Wearable Launch',
      priceLabel: 'Starting price:',
      price: 199,
      currency: 'GHS',
      image: 'https://images.unsplash.com/photo-1592478411213-681e4a689331?w=280&h=200&fit=crop',
      href: '/categories/wearable-tech',
      cta: 'SHOP NOW',
    },
  },
]

export const DEFAULT_CATEGORY_ID = 'smartphone'
export const DEFAULT_SUBCATEGORY_ID = 'iphone'
