const W = '?auto=compress&cs=tinysrgb&w=900'

export const CATEGORY_IMAGES = {
  smartphone: `https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg${W}`,
  tablet: `https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=80`,
  headphones: `https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg${W}`,
  camera: `https://images.pexels.com/photos/51383/pexels-photo-51383.jpeg${W}`,
  wearable: `https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg${W}`,
  smartwatch: `https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg${W}`,
  laptop: `https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80`,
  desktop: `https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&q=80`,
  keyboard: `https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg${W}`,
  mouse: `https://images.pexels.com/photos/256301/pexels-photo-256301.jpeg${W}`,
  monitor: `https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg${W}`,
  gaming: `https://images.pexels.com/photos/7915357/pexels-photo-7915357.jpeg${W}`,
  tv: `https://images.pexels.com/photos/5721908/pexels-photo-5721908.jpeg${W}`,
  appliance: `https://images.pexels.com/photos/4099237/pexels-photo-4099237.jpeg${W}`,
  electronics: `https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1400&q=80`,

  mensFashion: `https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg${W}`,
  womensFashion: `https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg${W}`,
  kidsFashion: `https://images.pexels.com/photos/36029/army-friends-girls-children.jpg${W}`,
  footwear: `https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg${W}`,
  accessories: `https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg${W}`,
  fashion: `https://images.pexels.com/photos/1485031/pexels-photo-1485031.jpeg${W}`,
  jewelry: `https://images.pexels.com/photos/1454227/pexels-photo-1454227.jpeg${W}`,

  furniture: `https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg${W}`,
  homeTextile: `https://images.pexels.com/photos/3734340/pexels-photo-3734340.jpeg${W}`,
  homeDecor: `https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg${W}`,
  smartHome: `https://images.pexels.com/photos/4792285/pexels-photo-4792285.jpeg${W}`,
  kitchen: `https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg${W}`,
  home: `https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg${W}`,

  strength: `https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg${W}`,
  cardio: `https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg${W}`,
  weights: `https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg${W}`,
  fitnessGear: `https://images.pexels.com/photos/703012/pexels-photo-703012.jpeg${W}`,
  activewear: `https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg${W}`,
  outdoor: `https://images.pexels.com/photos/1687845/pexels-photo-1687845.jpeg${W}`,
  sports: `https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg${W}`,

  makeup: `https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg${W}`,
  skincare: `https://images.pexels.com/photos/3786016/pexels-photo-3786016.jpeg${W}`,
  beauty: `https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg${W}`,

  grocery: `https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg${W}`,
  beverage: `https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg${W}`,
  freshProduce: `https://images.pexels.com/photos/533360/pexels-photo-533360.jpeg${W}`,

  automotive: `https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg${W}`,
  carParts: `https://images.pexels.com/photos/279949/pexels-photo-279949.jpeg${W}`,

  tools: `https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80`,
  powerTools: `https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=900&q=80`,
  handTools: `https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80`,
  construction: `https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80`,
  buildingMaterials: `https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=80`,
  safetyGear: `https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80`,
  measuringTools: `https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80`,
  industrial: `https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg${W}`,

  services: `https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg${W}`,
  office: `https://images.pexels.com/photos/37347/office-sitting-room-executive-sitting.jpg${W}`,

  toys: `https://images.pexels.com/photos/8613089/pexels-photo-8613089.jpeg${W}`,
  books: `https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg${W}`,
  pet: `https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg${W}`,

  babyMaternity: `https://images.pexels.com/photos/3875085/pexels-photo-3875085.jpeg${W}`,
  bagsLuggage: `https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg${W}`,

  phoneCase: `https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg${W}`,
  charger: `https://images.unsplash.com/photo-1591290619762-d2d9879b5e7b?auto=format&fit=crop&w=900&q=80`,
  agriculture: `https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80`,
  farm: `https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=900&q=80`,
  seeds: `https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=900&q=80`,
  generic: `https://images.unsplash.com/photo-1560394704-5c3d4a1c4d0e?auto=format&fit=crop&w=900&q=80`,
}

/** Exact slug → image (subcategory or parent). */
export const SLUG_IMAGE_MAP = {
  electronics: CATEGORY_IMAGES.electronics,
  fashion: CATEGORY_IMAGES.fashion,
  'home-kitchen': CATEGORY_IMAGES.home,
  home: CATEGORY_IMAGES.home,
  'beauty-personal-care': CATEGORY_IMAGES.beauty,
  'sports-outdoors': CATEGORY_IMAGES.sports,
  'toys-games': CATEGORY_IMAGES.toys,
  computing: CATEGORY_IMAGES.laptop,
  appliances: CATEGORY_IMAGES.appliance,
  'home-office': CATEGORY_IMAGES.office,
  'phones-accessories': CATEGORY_IMAGES.smartphone,
  'phones-tablets': CATEGORY_IMAGES.smartphone,
  smartphone: CATEGORY_IMAGES.smartphone,
  groceries: CATEGORY_IMAGES.grocery,
  automotive: CATEGORY_IMAGES.automotive,
  services: CATEGORY_IMAGES.services,
  'industrial-commercial-equipment': CATEGORY_IMAGES.industrial,
  'construction-tools': CATEGORY_IMAGES.tools,
  'construction-and-tools': CATEGORY_IMAGES.tools,
  agriculture: CATEGORY_IMAGES.agriculture,
  construction: CATEGORY_IMAGES.construction,
  'baby-and-maternity': CATEGORY_IMAGES.babyMaternity,
  'baby-maternity': CATEGORY_IMAGES.babyMaternity,
  baby: CATEGORY_IMAGES.babyMaternity,
  maternity: CATEGORY_IMAGES.babyMaternity,
  'bags-and-luggage': CATEGORY_IMAGES.bagsLuggage,
  'bags-luggage': CATEGORY_IMAGES.bagsLuggage,
  bags: CATEGORY_IMAGES.bagsLuggage,
  luggage: CATEGORY_IMAGES.bagsLuggage,

  'featured-phones': CATEGORY_IMAGES.smartphone,
  tablets: CATEGORY_IMAGES.tablet,
  'smart-watches': CATEGORY_IMAGES.smartwatch,
  chargers: CATEGORY_IMAGES.charger,
  'phone-cases': CATEGORY_IMAGES.phoneCase,
  cases: CATEGORY_IMAGES.phoneCase,
  seeds: CATEGORY_IMAGES.seeds,
  'farm-equipment': CATEGORY_IMAGES.farm,
  irrigation: CATEGORY_IMAGES.agriculture,
  livestock: CATEGORY_IMAGES.farm,
  fertilizers: CATEGORY_IMAGES.seeds,
  'power-tools': CATEGORY_IMAGES.powerTools,
  'hand-tools': CATEGORY_IMAGES.handTools,
  'safety-gear': CATEGORY_IMAGES.safetyGear,
  'building-materials': CATEGORY_IMAGES.buildingMaterials,
  'measuring-tools': CATEGORY_IMAGES.measuringTools,
  storage: CATEGORY_IMAGES.laptop,

  smartphones: CATEGORY_IMAGES.smartphone,
  'headphones-earbuds-accessories': CATEGORY_IMAGES.headphones,
  headphone: CATEGORY_IMAGES.headphones,
  'cameras-video': CATEGORY_IMAGES.camera,
  'camera-photo': CATEGORY_IMAGES.camera,
  'wearable-tech': CATEGORY_IMAGES.wearable,
  watches: CATEGORY_IMAGES.wearable,
  'mens-wear': CATEGORY_IMAGES.mensFashion,
  'womens-wear': CATEGORY_IMAGES.womensFashion,
  'kids-wear': CATEGORY_IMAGES.kidsFashion,
  footwear: CATEGORY_IMAGES.footwear,
  accessories: CATEGORY_IMAGES.accessories,
  'kitchen-appliances': CATEGORY_IMAGES.appliance,
  'home-textile': CATEGORY_IMAGES.homeTextile,
  furniture: CATEGORY_IMAGES.furniture,
  'home-decor': CATEGORY_IMAGES.homeDecor,
  'smart-home': CATEGORY_IMAGES.smartHome,
  'strength-training': CATEGORY_IMAGES.strength,
  'cardio-equipment': CATEGORY_IMAGES.cardio,
  'free-weights': CATEGORY_IMAGES.weights,
  'fitness-accessories': CATEGORY_IMAGES.fitnessGear,
  activewear: CATEGORY_IMAGES.activewear,

  laptops: CATEGORY_IMAGES.laptop,
  desktops: CATEGORY_IMAGES.desktop,
  macbook: CATEGORY_IMAGES.laptop,
  'gaming-pcs': CATEGORY_IMAGES.gaming,
  keyboards: CATEGORY_IMAGES.keyboard,
  mice: CATEGORY_IMAGES.mouse,
  monitors: CATEGORY_IMAGES.monitor,
  'mobile-accessories': CATEGORY_IMAGES.phoneCase,
  cases: CATEGORY_IMAGES.phoneCase,
  chargers: CATEGORY_IMAGES.charger,
  'power-banks': CATEGORY_IMAGES.charger,
  'gaming-console': CATEGORY_IMAGES.gaming,
  playstation: CATEGORY_IMAGES.gaming,
  xbox: CATEGORY_IMAGES.gaming,
  nintendo: CATEGORY_IMAGES.gaming,
  iphone: CATEGORY_IMAGES.smartphone,
  samsung: CATEGORY_IMAGES.smartphone,
  'over-ear': CATEGORY_IMAGES.headphones,
  'in-ear': CATEGORY_IMAGES.headphones,
  wireless: CATEGORY_IMAGES.headphones,
  dslr: CATEGORY_IMAGES.camera,
  mirrorless: CATEGORY_IMAGES.camera,
  action: CATEGORY_IMAGES.camera,
  'tv-appliances': CATEGORY_IMAGES.tv,
  'smart-tv': CATEGORY_IMAGES.tv,
}

/** Parent slug default when child cannot be matched. */
export const PARENT_DEFAULT_IMAGES = {
  electronics: CATEGORY_IMAGES.electronics,
  fashion: CATEGORY_IMAGES.fashion,
  'home-kitchen': CATEGORY_IMAGES.home,
  'sports-outdoors': CATEGORY_IMAGES.sports,
  'beauty-personal-care': CATEGORY_IMAGES.beauty,
  computing: CATEGORY_IMAGES.laptop,
  'phones-accessories': CATEGORY_IMAGES.smartphone,
  'phones-tablets': CATEGORY_IMAGES.smartphone,
  smartphone: CATEGORY_IMAGES.smartphone,
  groceries: CATEGORY_IMAGES.grocery,
  automotive: CATEGORY_IMAGES.automotive,
  services: CATEGORY_IMAGES.services,
  'industrial-commercial-equipment': CATEGORY_IMAGES.industrial,
  'construction-tools': CATEGORY_IMAGES.tools,
  'construction-and-tools': CATEGORY_IMAGES.tools,
  construction: CATEGORY_IMAGES.construction,
  agriculture: CATEGORY_IMAGES.agriculture,
  appliances: CATEGORY_IMAGES.appliance,
  'toys-games': CATEGORY_IMAGES.toys,
  'home-office': CATEGORY_IMAGES.office,
  'baby-and-maternity': CATEGORY_IMAGES.babyMaternity,
  'baby-maternity': CATEGORY_IMAGES.babyMaternity,
  'bags-and-luggage': CATEGORY_IMAGES.bagsLuggage,
  'bags-luggage': CATEGORY_IMAGES.bagsLuggage,
}

/**
 * Keyword rules evaluated in order — first match wins.
 * Patterns run against `${slug} ${label}`.
 */
export const CATEGORY_IMAGE_KEYWORD_RULES = [
  { pattern: /\b(featured phone|flagship phone|smartphone|smart phone|iphone|android)\b/i, image: CATEGORY_IMAGES.smartphone },
  { pattern: /\b(tablet|ipad|galaxy tab)\b/i, image: CATEGORY_IMAGES.tablet },
  { pattern: /\b(smart.?watch|wearable|fitness band)\b/i, image: CATEGORY_IMAGES.smartwatch },
  { pattern: /\b(charger|cable|power bank|adapter|charging)\b/i, image: CATEGORY_IMAGES.charger },
  { pattern: /\b(phone|mobile)\b/i, image: CATEGORY_IMAGES.smartphone },
  { pattern: /\b(headphone|earbud|earphone|audio|speaker|soundbar|over-ear|in-ear|noise.?cancelling)\b/i, image: CATEGORY_IMAGES.headphones },
  { pattern: /\b(camera|dslr|mirrorless|lens|photography|gopro|action cam)\b/i, image: CATEGORY_IMAGES.camera },
  { pattern: /\b(watch|wearable|smartwatch|fitness band|vr headset)\b/i, image: CATEGORY_IMAGES.wearable },
  { pattern: /\b(laptop|macbook|notebook|ultrabook|chromebook)\b/i, image: CATEGORY_IMAGES.laptop },
  { pattern: /\b(desktop|pc tower|gaming pc|workstation)\b/i, image: CATEGORY_IMAGES.desktop },
  { pattern: /\b(keyboard|mechanical keyboard)\b/i, image: CATEGORY_IMAGES.keyboard },
  { pattern: /\b(mouse|trackpad|pointing)\b/i, image: CATEGORY_IMAGES.mouse },
  { pattern: /\b(monitor|display|screen)\b/i, image: CATEGORY_IMAGES.monitor },
  { pattern: /\b(playstation|xbox|nintendo|gaming console|game console)\b/i, image: CATEGORY_IMAGES.gaming },
  { pattern: /\b(tv|television|smart tv|home theater)\b/i, image: CATEGORY_IMAGES.tv },
  { pattern: /\b(refrigerator|washer|dryer|microwave|toaster|blender|appliance)\b/i, image: CATEGORY_IMAGES.appliance },

  { pattern: /\b(men'?s wear|menswear|men fashion|suit|blazer|shirt)\b/i, image: CATEGORY_IMAGES.mensFashion },
  { pattern: /\b(women'?s wear|womenswear|dress|heels)\b/i, image: CATEGORY_IMAGES.womensFashion },
  { pattern: /\b(baby|maternity|infant|newborn|nursery|stroller|diaper|feeding)\b/i, image: CATEGORY_IMAGES.babyMaternity },
  { pattern: /\b(bags?|luggage|suitcase|backpack|travel bag|handbag|tote|carry.?on)\b/i, image: CATEGORY_IMAGES.bagsLuggage },
  { pattern: /\b(kid|children|baby wear|toddler)\b/i, image: CATEGORY_IMAGES.kidsFashion },
  { pattern: /\b(shoe|footwear|sneaker|boot|sandal|heel)\b/i, image: CATEGORY_IMAGES.footwear },
  { pattern: /\b(jewelry|necklace|ring|bracelet|earring)\b/i, image: CATEGORY_IMAGES.jewelry },
  { pattern: /\b(accessor|belt|scarf|hat|sunglass)\b/i, image: CATEGORY_IMAGES.accessories },
  { pattern: /\b(fashion|apparel|clothing|cloth)\b/i, image: CATEGORY_IMAGES.fashion },

  { pattern: /\b(furniture|sofa|couch|table|chair|bed frame)\b/i, image: CATEGORY_IMAGES.furniture },
  { pattern: /\b(textile|towel|linen|bedding|curtain|pillow)\b/i, image: CATEGORY_IMAGES.homeTextile },
  { pattern: /\b(decor|vase|candle|wall art|ornament)\b/i, image: CATEGORY_IMAGES.homeDecor },
  { pattern: /\b(smart home|home automation|alexa|google home)\b/i, image: CATEGORY_IMAGES.smartHome },
  { pattern: /\b(kitchen|cookware|utensil|dining)\b/i, image: CATEGORY_IMAGES.kitchen },
  { pattern: /\b(home|household)\b/i, image: CATEGORY_IMAGES.home },

  { pattern: /\b(weight|dumbbell|kettlebell|barbell|strength)\b/i, image: CATEGORY_IMAGES.weights },
  { pattern: /\b(cardio|treadmill|elliptical|exercise bike|gym machine)\b/i, image: CATEGORY_IMAGES.cardio },
  { pattern: /\b(fitness|workout|training equipment|gym)\b/i, image: CATEGORY_IMAGES.strength },
  { pattern: /\b(activewear|sportswear|yoga|athletic wear)\b/i, image: CATEGORY_IMAGES.activewear },
  { pattern: /\b(camping|hiking|outdoor|trail)\b/i, image: CATEGORY_IMAGES.outdoor },
  { pattern: /\b(sport|football|basketball|cricket|athletic)\b/i, image: CATEGORY_IMAGES.sports },

  { pattern: /\b(makeup|cosmetic|lipstick|foundation|mascara)\b/i, image: CATEGORY_IMAGES.makeup },
  { pattern: /\b(skincare|skin care|moisturizer|serum|lotion)\b/i, image: CATEGORY_IMAGES.skincare },
  { pattern: /\b(beauty|personal care|grooming|fragrance|perfume)\b/i, image: CATEGORY_IMAGES.beauty },

  { pattern: /\b(agriculture|farming|farm|crop|livestock|irrigation|fertilizer|seed)\b/i, image: CATEGORY_IMAGES.agriculture },
  { pattern: /\b(grocer|grocery|pantry|snack|food|provision)\b/i, image: CATEGORY_IMAGES.grocery },
  { pattern: /\b(beverage|drink|juice|water bottle)\b/i, image: CATEGORY_IMAGES.beverage },
  { pattern: /\b(produce|fruit|vegetable|fresh food)\b/i, image: CATEGORY_IMAGES.freshProduce },

  { pattern: /\b(car|automotive|vehicle|motor|tire|tyre)\b/i, image: CATEGORY_IMAGES.automotive },
  { pattern: /\b(auto part|spare part|engine part)\b/i, image: CATEGORY_IMAGES.carParts },

  { pattern: /\b(tool|hardware|drill|hammer|wrench|screwdriver)\b/i, image: CATEGORY_IMAGES.tools },
  { pattern: /\b(construction|building material|cement|plumbing)\b/i, image: CATEGORY_IMAGES.construction },
  { pattern: /\b(industrial|commercial equipment|machinery|factory)\b/i, image: CATEGORY_IMAGES.industrial },

  { pattern: /\b(service|consulting|repair|installation|support)\b/i, image: CATEGORY_IMAGES.services },
  { pattern: /\b(office|stationery|desk|printer)\b/i, image: CATEGORY_IMAGES.office },

  { pattern: /\b(toy|game|puzzle|lego)\b/i, image: CATEGORY_IMAGES.toys },
  { pattern: /\b(book|novel|reading|stationery)\b/i, image: CATEGORY_IMAGES.books },
  { pattern: /\b(pet|dog|cat|animal)\b/i, image: CATEGORY_IMAGES.pet },

  { pattern: /\b(case|cover|screen protector)\b/i, image: CATEGORY_IMAGES.phoneCase },
  { pattern: /\b(charger|cable|power bank|adapter)\b/i, image: CATEGORY_IMAGES.charger },
  { pattern: /\b(electronic|gadget|tech|device)\b/i, image: CATEGORY_IMAGES.electronics },
  { pattern: /\b(computing|computer)\b/i, image: CATEGORY_IMAGES.laptop },
]
